#!/bin/bash -vx
#########
# Setup #
#########
DATETIME=$(date "+%d-%m-%y_%H:%M")
SCRIPTPATH="$( cd -- "$(dirname "$0")" > /dev/null 2>&1 ; pwd -P )"
LOGFILE="$SCRIPTPATH/logs/Hardening_Check_$DATETIME.log"
RESULT=0
FAILCNT=0
touch "$LOGFILE"
#####################
# Utility Functions #
#####################
execute() {
	$($1 "$LOGFILE")
	FAILCNT=$(($FAILCNT+"$?"))
}

########################
# Execute req1a script #
########################
execute "$SCRIPTPATH/req1a"

########################
# Execute req1b script #
########################
execute "$SCRIPTPATH/req1b"

#######################
# Execute req1c script #
########################
execute "$SCRIPTPATH/req1c"

########################
# Execute req1d script #
########################
execute "$SCRIPTPATH/req1d"

########################
# Execute req1e script #
########################
execute "$SCRIPTPATH/req1e"

#######################
# Evaluate Fail count #
#######################
sed -i "1s/^/Failure: $FAILCNT|5 \n/" "$LOGFILE"
sed -i "1s/^/##################### RESULTS ($DATETIME) #####################\n/" "$LOGFILE"
echo "RHEL 9 Hardening $DATETIME, FAILURES: $FAILCNT|5"
cat "$LOGFILE"

##############################
# Send Mail report if errors #
##############################
#if [ "$FAILCNT" -gt 0 ]
#then
#	cat "$LOGFILE" | mail -s "RHEL 9 Hardening $DATETIME, FAILURES: $FAILCNT|5" justin.gxh98@gmail.com
#fi
