#!/bin/bash
#########
# Setup #
#########
DATETIME=$(date "+%d-%m-%y_%H:%M")
LOGFILE="$(pwd)/logs/Hardening_Check_$DATETIME.log"
RESULT=0
FAILCNT=0

#####################
# Utility Functions #
#####################
execute() {
	./$1 "$LOGFILE"
	FAILCNT=$(($FAILCNT+"$?"))
}

########################
# Execute req1a script #
########################
execute req1a

########################
# Execute req1b script #
########################
execute req1b

#######################
# Execute req1c script #
########################
execute req1c

########################
# Execute req1d script #
########################
execute req1d

########################
# Execute req1e script #
########################
execute req1e

#######################
# Evaluate Fail count #
#######################
sed -i "1s/^/Failure: $FAILCNT \n/" "$LOGFILE"
sed -i "1s/^/##################### RESULTS ($DATETIME) #####################\n/" "$LOGFILE"

####################
# Send Mail report #
####################
cat "$LOGFILE" | mail -s "RHEL 9 Hardening $DATETIME, FAILURES: $FAILCNT" fanlit1998@gmail.com

