#!/bin/bash
#########
# Setup #
#########
DATETIME=$(date "+%d-%m-%y_%H:%M:%S")
SCRIPTPATH="$( cd -- "$(dirname "$0")" > /dev/null 2>&1 ; pwd -P )"
LOGFILE="$SCRIPTPATH/logs/Hardening_Check_$DATETIME.log"
RESULT=0
FAILCNT=0
MACHNAME=$(hostname -f)
touch "$LOGFILE"

#####################
# Utility Functions #
#####################
execute() {
	$($1 "$LOGFILE")
	FAILCNT=$(($FAILCNT+"$?"))
	echo "" >> $LOGFILE
}

########################
# Execute req1a script #
########################
execute "$SCRIPTPATH/1a_PermitRootLogin"

########################
# Execute req1b script #
########################
execute "$SCRIPTPATH/1b_PermitEmptyPasswords"

#######################
# Execute req1c script #
########################
execute "$SCRIPTPATH/1c_Protocol"

########################
# Execute req1d script #
########################
execute "$SCRIPTPATH/1d_PASS_MAX_DAYS"

########################
# Execute req1e script #
########################
execute "$SCRIPTPATH/1e_System_acc_nologin"

#######################
# Evaluate Fail count #
#######################
sed -i "1s/^/Machine: $MACHNAME       Failure: $FAILCNT|5 \n/" "$LOGFILE"
sed -i "1s/^/##################### RESULTS ($DATETIME) #####################\n/" "$LOGFILE"
echo "$MACHNAME RHEL 9 CIS Compliance check ($DATETIME), FAILURES: $FAILCNT|5"
cat "$LOGFILE"

##############################
# Send Mail report if errors #
##############################
#if [ "$FAILCNT" -gt 0 ]
#then
#	cat "$LOGFILE" | mail -s "$MACHNAME: RHEL 9 Hardening $DATETIME, FAILURES: $FAILCNT|5" justin.gxh98@gmail.com
#fi
