#!/bin/bash

#########
# Setup #
#########

DATETIME=$(date "+%d-%m-%y %r")
SUBJFILE='/etc/login.defs'
KEY='PASS_MAX_DAYS'
REQ='1D'
STDOUTLOGFILE=$1
echo "" >> "$STDOUTLOGFILE"
echo "# $REQ. Ensure password expiration is 90 days or less #########################" >> "$STDOUTLOGFILE"
echo "Subject File: $SUBJFILE" >> "$STDOUTLOGFILE"
echo "Key: $KEY" >> "$STDOUTLOGFILE"

#############################
# 1: Subject file not found #
#############################
if [ ! -f "$SUBJFILE" ]
then
        echo "Req $REQ Testcase 1: FAIL: Subject file not found." >> "$STDOUTLOGFILE"
	exit 1
fi

####################
# 2: Key not found #
####################
if [ $( grep "^\s*$KEY\s*" "$SUBJFILE" | wc -l) -eq 0 ]
then
	echo "Req $REQ Testcase 2: FAIL: Key cannot be found." >> "$STDOUTLOGFILE"
	exit 1
fi

#######################################
# 3: Invalid entry (In-line comments) #
#######################################
CMDOUT=$( grep "^\s*$KEY\s*" "$SUBJFILE" | tail -1 | grep -iP "^\s*PASS_MAX_DAYS\s+(#.*)$" | wc -l)
if [ "$CMDOUT" -ne 0 ]
then
        echo "Req $REQ Testcase 3: FAIL: Invalid entry, in-line comments" >> "$STDOUTLOGFILE"
        exit 1
fi

##########################
# 4: No associated value #
##########################
CMDOUT=$( grep "^\s*$KEY\s*" "$SUBJFILE" | tail -1 | grep "^\s*$KEY\s*$" | wc -l)
if [ "$CMDOUT" -ne 0 ]
then
	echo "Req $REQ Testcase 4: FAIL: No value." >> "$STDOUTLOGFILE"
	exit 1
fi

######################
# 5. Multiple values #
######################
CMDOUT=$( grep -E "^\s*$KEY\s+" $SUBJFILE | tail -1 | grep -E "^\s*$KEY\s+(-*\S+\s+\S+\s*)" $SUBJFILE | wc -l)
if [ "$CMDOUT" -ne 0 ]
then
        echo "Req $REQ Testcase 5: FAIL: Multiple values" >> "$STDOUTLOGFILE"
        exit 1
fi

###############################
# Shared values: Testcase 6-8 #
###############################
TOCONVERT=$(grep -E "^\s*$KEY\s+" $SUBJFILE | tail -1 | awk '{$1=$1};{print $2}')
CONVERTED=$(printf "%d" $TOCONVERT)

###########################################
# 6a. Invalid value (Unconvertable value) #
###########################################
if [ "$?" -ne 0 ]
then
	echo "Req $REQ Testcase 6a: FAIL: Invalid value (Unconvertable value)" >> "$STDOUTLOGFILE"
	exit 1
fi

#####################################
# 6b. Invalid value (Invalid range) #
#####################################
if [[ $CONVERTED -lt -1 || $CONVERTED -gt 99999 ]]
then
	echo "Req $REQ Testcase 6b: FAIL: Invalid value (Invalid range)." >> "$STDOUTLOGFILE"
	exit 1
fi

##########################
# 7. Non-Compliant value #
##########################
if [[ $CONVERTED -eq -1 || $CONVERTED -gt 90 ]]
then
        echo "Req $REQ Testcase 7: FAIL: Non-compliant value." >> "$STDOUTLOGFILE"
        exit 1
fi

######################
# 8. Compliant value #
######################
if [[ $CONVERTED -ge 0 && $CONVERTED -le 90 ]]
then
        echo "Req $REQ: PASS" >> "$STDOUTLOGFILE"
        exit 0
fi

# If it comes to this line, it means value input is outside the scope of the testcases
echo "Req $REQ: FAIL: Unexpected value" >> "$STDOUTLOGFILE"
exit 1
