#!/bin/bash

#########
# Setup #
#########

DATETIME=$(date "+%d-%m-%y %r")
SUBJFILE='/etc/ssh/sshd_config'
KEY='Protocol'
REQ='1C'
# STDOUTLOGFILE="req"$REQ"_$(date "+%d-%m-%y").log"
STDOUTLOGFILE=$1
#STARTFAIL=0
echo "" >> "$STDOUTLOGFILE"
echo "# $REQ. Ensure SSH Protocol is set to 2  #########################" >> "$STDOUTLOGFILE"
echo "Subject File: $SUBJFILE" >> "$STDOUTLOGFILE"
echo "Key: $KEY" >> "$STDOUTLOGFILE"

##############################
# 1: Check SSH service start #
##############################
#systemctl restart sshd &> /dev/null
#if [ "$?" -ne 0 ]
#then
#	echo "Req $REQ Testcase 1: FAIL:SSH service cannot be started." >> "$STDOUTLOGFILE"
#	STARTFAIL=1
#fi

#############################
# 1: Subject File not Found #
#############################
if [ ! -f "$SUBJFILE" ]
then
        echo "Req $REQ Testcase 1: FAIL: Subject file not found." >> "$STDOUTLOGFILE"
	exit 1
fi

####################
# 2: Key not found #
####################
if [ $( grep -i "^\s*$KEY\s*" "$SUBJFILE" | wc -l) -eq 0 ]
then
	echo "Req $REQ Testcase 2: FAIL: Key cannot be found." >> "$STDOUTLOGFILE"
	exit 1
fi

##########################
# 3: No associated value #
##########################
CMDOUT=$( grep -i "^\s*$KEY\s*" "$SUBJFILE" | head -1 | grep -iP "^\s*$KEY\s*(#.*)*$" | wc -l)
if [ "$CMDOUT" -ne 0 ]
then
	echo "Req $REQ Testcase 3: FAIL: No value." >> "$STDOUTLOGFILE"
	exit 1
fi

######################
# 4. Multiple values #
######################
CMDOUT=$(grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | sed 's/#.*//' | sed 's/\s*,\s*/,/g' | grep -iP "^\s*$KEY\s+\S+\s+\S+" | wc -l)
if [ "$CMDOUT" -ne 0  ]
then
        echo "Req $REQ Testcase 4: FAIL: Multiple values." >> "$STDOUTLOGFILE"
        exit 1
fi

####################
# 5. Invalid value #
####################
CMDOUT=$(grep -E "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+(?!\s*(1|1(\s*,\s*1)+|1(\s*,\s*2)+|2|2(\s*,\s*1)+|2(\s*,\s*2)+)\s*(#.*)*$)" | wc -l)
if [ "$CMDOUT" -ne 0  ]
then
	echo "Req $REQ Testcase 5: FAIL: Invalid value." >> "$STDOUTLOGFILE"
	exit 1
fi

##########################
# 6. Non-Compliant value #
##########################
CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+(?!\s*(2|2(\s*,\s*2)+)\s*(#.*)*$)" | wc -l)
if [ "$CMDOUT" -ne 0  ]
then
        echo "Req $REQ Testcase 6: FAIL: Non-compliant value." >> "$STDOUTLOGFILE"
        exit 1
fi

######################
# 7. Compliant value #
######################
CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+(2|2(\s*,\s*2)+)\s*(#.*)*$" | wc -l)
if [ "$CMDOUT" -eq 1 ]
then
        echo "Req $REQ: PASS" >> "$STDOUTLOGFILE"
        exit 0
fi

#if [ "$STARTFAIL" -eq 1 ]
#then
#	exit 1
#fi

# If it comes to this line, it means value input is outside the scope of the testcases
echo "Req $REQ: FAIL: Unexpected value" >> "$STDOUTLOGFILE"
exit 1
