#!/bin/bash

#########
# Setup #
#########

DATETIME=$(date "+%d-%m-%y %r")
SUBJFILE='/etc/ssh/sshd_config'
KEY='PermitEmptyPasswords'
REQ='1B'
#STDOUTLOGFILE="req"$REQ"_$(date "+%d-%m-%y").log"
STDOUTLOGFILE=$1
STARTFAIL=0
echo "" >> "$STDOUTLOGFILE"
echo "#################### $REQ. Ensure SSH PermitEmptyPasswords is disabled  #########################" >> "$STDOUTLOGFILE"
echo "Subject File: $SUBJFILE" >> "$STDOUTLOGFILE"
echo "Key: $KEY" >> "$STDOUTLOGFILE"

##############################
# 1: Check SSH service start #
##############################
systemctl restart sshd &> /dev/null
if [ "$?" -ne 0 ]
then
	echo "Req $REQ Testcase 1: FAIL: SSH service cannot be started." >> "$STDOUTLOGFILE"
	STARTFAIL=1
fi

#############################
# 2: Subject File not Found #
#############################
if [ ! -f "$SUBJFILE" ]
then
        echo "Req $REQ Testcase 2: FAIL: Subject file not found." >> "$STDOUTLOGFILE"
	exit 1
fi

####################
# 2: Key not found #
####################
if [ $( grep -i "^\s*$KEY\s*" "$SUBJFILE" | wc -l) -eq 0 ]
then
	echo "Req $REQ Testcase 3: FAIL: Key cannot be found." >> "$STDOUTLOGFILE"
	exit 1
fi

##########################
# 3: No associated value #
##########################
CMDOUT=$( grep -i "^\s*$KEY\s*" "$SUBJFILE" | head -1 | grep -i "^\s*$KEY\s*$" | wc -l)
if [ "$CMDOUT" -ne 0 ]
then
	echo "Req $REQ Testcase 4: FAIL: No value." >> "$STDOUTLOGFILE"
	exit 1
fi

######################
# 4. Multiple values #
######################
CMDOUT=$( grep -iE "^\s*$KEY\s+" "$SUBJFILE" | head -1 | grep -iP "^\s*$KEY\s+.+\s+.+" | wc -l)
if [ "$CMDOUT" -ne 0  ]
then
        echo "Req $REQ Testcase 5: FAIL: Multiple values." >> "$STDOUTLOGFILE"
        exit 1
fi

####################
# 5. Invalid value #
####################
CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+((?!yes|no)\s*)" | wc -l)
if [ "$CMDOUT" -ne 0  ]
then
	echo "Req $REQ Testcase 6: FAIL: Invalid value." >> "$STDOUTLOGFILE"
	exit 1
fi

##########################
# 6. Non-Compliant value #
##########################
CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iP "^\s*$KEY\s+((?!no)\s*)" | wc -l)
if [ "$CMDOUT" -ne 0  ]
then
        echo "Req $REQ Testcase 7: FAIL: Non-compliant value." >> "$STDOUTLOGFILE"
        exit 1
fi

######################
# 7. Compliant value #
######################
CMDOUT=$( grep -iE "^\s*$KEY\s+" $SUBJFILE | head -1 | grep -iE "^\s*$KEY\s+no\s*$" | wc -l)
if [[ "$CMDOUT" -ne 0 && $STARTFAIL -ne 1 ]]
then
        echo "Req $REQ: PASS" >> "$STDOUTLOGFILE"
        exit 0
fi

if [ "$STARTFAIL" -eq 1 ]
then
	exit 1
fi
