#!/bin/bash

#########
# Setup #
#########

DATETIME=$(date "+%d-%m-%y %r")
SUBJFILE='/etc/passwd'
KEY='user:pass:uid:gid:gesoc:home_dir:command/shell'
REQ='1E'
STDOUTLOGFILE="req"$REQ"_$(date "+%d-%m-%y").log"
echo "" >> "$STDOUTLOGFILE"
echo "#################### $REQ. $(date "+%d-%m-%y %r") #########################" >> "$STDOUTLOGFILE"
echo "Subject File: $SUBJFILE" >> "$STDOUTLOGFILE"
echo "Key: $KEY" >> "$STDOUTLOGFILE"

#############################
# 1: Subject file not found #
#############################
if [ ! -f "$SUBJFILE" ]
then
        echo "Req $REQ Testcase 1: Subject file not found." >> "$STDOUTLOGFILE"
        exit 1
fi

#################
# Command setup #
#################
# system accounts: sync, halt , shutdown can be safely put to /sbin/nologin: https://access.redhat.com/solutions/47392
# CMDOUT= $(grep -P "^\s*(.+):x*:\d{1,3}:\d{1,3}:.*:.*:(?!(/usr/sbin/nologin|/sbin/nologin|/bin/false))" $SUBJFILE | grep -P "^\s*(?!(sync|showdown|halt))")
# CMDOUT=$(grep -P "^\s*.+:x*:((\d{1,3}:\d{1,3})|(65534:65534)):.*:.*:(?!(/usr/sbin/nologin|/sbin/nologin|/bin/false))" $SUBJFILE)
# echo "$CMDOUT"
CMDOUT=$(awk -F: '($1!~/^(root|halt|sync|shutdown|nfsnobody)$/ && ($3<'"$(awk '/^\s*UID_MIN/{print $2}' /etc/login.defs)"' || $3 == 65534) && $7!~/^(\/usr)?\/sbin\/nologin$/) { print $1 }' /etc/passwd)
echo $CMDOUT
