#!/bin/bash

#########
# Setup #
#########

DATETIME=$(date "+%d-%m-%y %r")
SUBJFILE='/etc/passwd'
KEY='user:pass:uid:gid:gesoc:home_dir:command/shell'
REQ='1E'
STDOUTLOGFILE="req"$REQ"_$(date "+%d-%m-%y").log"
echo "" >> "$STDOUTLOGFILE"
echo "#################### $REQ. $(date "+%d-%m-%y %r") #########################" >> "$STDOUTLOGFILE"
echo "Subject File: $SUBJFILE" >> "$STDOUTLOGFILE"
echo "Key: $KEY" >> "$STDOUTLOGFILE"

#############################
# 1: Subject file not found #
#############################
if [ ! -f "$SUBJFILE" ]
then
        echo "Req $REQ Testcase 1: Subject file not found." >> "$STDOUTLOGFILE"
        exit 1
fi

