#!/bin/bash
SUBJFILE='/etc/login.defs'
KEY='PASS_MAX_DAYS'
convert(){
        # local SUBJLINE=$(grep -E -m 1 "^\s*$KEY\s+" $SUBJFILE | awk '{$1=$1};{print $2}')
        SUBJLINE=$1
	local CHECKED=""
        # Check and convert HEX -> DECI
        if [ $( echo "$SUBJLINE" | grep -E -m 1 "^0x[1-9a-fA-F]+" | wc -l) -eq 1 ]
        then
                CHECKED=$(echo "$SUBJLINE" | sed "s/^0x//"| sed "y/abcdef/ABCDEF/")
		echo "$((16#$CHECKED))"

        # Check and convert OCT -> DECI
        elif [ $( echo "$SUBJLINE" | grep -E -m 1 "^0[0-7]+" | wc -l) -eq 1 ]
        then
                CHECKED=$(echo "$SUBJLINE" | sed "s/^0//")
		echo "$((8#$CHECKED))"
        # Check DECI
        elif [ $( echo "$SUBJLINE" | grep -E -m 1 "^(-1|0|[0-9]{1,5})" | wc -l) -eq 1 ]
        then
		echo "$SUBJLINE"

        # Check INVALID
        else
                echo "-2"
        fi
}

CONVERTED2=$(convert "$(grep -E -m 1 "^\s*$KEY\s+" $SUBJFILE | awk '{$1=$1};{print $2}')")
echo "$CONVERTED2"
