#!/bin/bash
SUBJFILE='/etc/passwd'
CMDOUT=$(grep -P "^\s*.+:x*:((\d{1,3}:\d{1,3})|(65534:65534)):.*:.*:(?!(/usr/sbin/nologin|/sbin/nologin|/bin/false))" $SUBJFILE)
# UNLOCKED=$(echo "$CMDOUT" | awk "{if($2 == 'PS'{print $1})}")
echo "$CMDOUT" | awk "{FS=":"}{print $1}" |while read line 
echo "$UNLOCKED"
